### ISSUE TITLE
envoy seems incorrect

### ISSUE THREAD

**Issue by HAOYUatHZ** [fluidex/rollup-state-manager#160]
http://localhost:8767/api/l2_blocks

`upstream connect error or disconnect/reset before headers. reset reason: connection failure`

**Comment by silathdiir** [comment]
After merging the PR #166 , please  test this URL `http://localhost:8766/api/l2_blocks` (port `8766`).

**Comment by lispc** [comment]
ubuntu@ip-172-31-29-22:~/repos/Fluidex/fluidex-backend$ curl http://localhost:8766/api/l2_blocks
upstream connect error or disconnect/reset before headers. reset reason: connection failure
