### ISSUE TITLE
migrate block test from ts to rs

### ISSUE THREAD

**Issue by lispc** [Fluidex/rollup-state-manager#33]
In ts, <https://github.com/Fluidex/circuits/blob/0a0778b22ceea97d57d131a5d8439ce7fad4021c/test/export_all_tests.ts#L32> <https://github.com/Fluidex/circuits/blob/master/test/block.ts> this test case writes testdata into testdata/Block_2_2_2_2 then [uses snarkit to test it](https://github.com/Fluidex/circuits/blob/master/tools/fast_test.sh).

We need to migrate this test into rust side.

We need to implement WitnessGenerator.withdraw method, and rewrite block.ts in rust.

As for codes in export_all_test.rs, <https://github.com/Fluidex/rollup-state-manager/blob/master/src/test_utils/circuit.rs> and <https://github.com/Fluidex/rollup-state-manager/tree/master/tests/export_circuit> maybe useful.

Notice: only block.ts needs to be migrated. We don't need to migrate other tests in circuits/test folder.

**Comment by lispc** [comment]
@HAOYUatHZ any idea on folder structure?

**Comment by HAOYUatHZ** [comment]
> @HAOYUatHZ any idea on folder structure?

Maybe after we finish migrating them all, then I could reorganize the folder structure

**Comment by lispc** [comment]
ok
