### ISSUE TITLE
feat: feed MQ messages to rollup-state-manager, and then write to prover-cluster DB

### ISSUE THREAD

**Issue by HAOYUatHZ** [Fluidex/rollup-state-manager#66]
## STEP 1

change rollup-state-manager/tests/global_state/gen_testcase.rs#L74 `load_msgs_from_file` to `load_msgs_from_mq`
(we would still like to keep rollup-state-manager/tests/global_state/gen_testcase.rs there , so it'd be better to implement a new rollup-state-manager/src/bin/main.rs following the similar logic in rollup-state-manager/tests/global_state/gen_testcase.rs

Requirements:

1. implement `load_msgs_from_mq`

**keep `load_msgs_from_mq` running** (like, forever :P), read messages from MQ.
The MQ is set up by dingir-exchange, and its endpoint is https://github.com/Fluidex/dingir-exchange/blob/master/config.yaml#L4 . You may borrow some codes from https://github.com/Fluidex/dingir-exchange/blob/master/src/bin/test_unifymessenger.rs to read messages.

which messages to read? (let's work on these 3 first, and leave others as future work)
+ types::matchengine::messages::BalanceMessage (topic: "orders")
+ types::matchengine::messages::TradeMessage (topic: "trades")
+ types::matchengine::messages::OrderMessage (topic: "orders")

2. when receiving messages, use `_sender: crossbeam_channel::Sender<WrappedMessage>` to send `WrappedMessage` to `msg_receiver` via channel.

the messages then will be processed by `replay_msgs`

`replay_msgs` converts `WrappedMessage` to `L2Block` and then `L2Block` will be sent to `block_receiver` using `block_sender`

We would also need to modify `replay_msgs` a little bit.

Previously, `msg_receiver.iter()` collects all the messages parsed from `load_msgs_from_file`, and then run `witgen.flush_with_nop();` at the end.

We now would like to **keep `replay_msgs` running**, and then `witgen.flush_with_nop()` every `*test_utils::params::NTXS`.

block_receiver will recieve some data to write into DB.

(So in this sense we write into DB every time we get a `L2Block` ready, that is, every time we receive `*test_utils::params::NTXS` messages)

+ which DB to write into?
    * https://github.com/Fluidex/prover-cluster/blob/master/docker/docker-compose.yaml
+ how to write into the DB? in which format?
    * there is only 1 table in the DB, defined here: https://github.com/Fluidex/prover-cluster/blob/master/migrations/20210330142700_task.sql
    * we already have `L2Block`s generated by witgen, follow https://github.com/Fluidex/rollup-state-manager/blob/master/tests/global_state/export_circuit.rs#L34 to retrieve `input` and `ouput`, we need to write each  `input`+`ouput` pair into DB
        - for now you could just use unique task_id，I will adding auto_increment stuff in prover-cluster DB later
        - https://github.com/Fluidex/prover-cluster/blob/832f688759eef9b0c4454ba6e3061425eaed7a5f/migrations/20210330142700_task.sql#L5 is `block` for now
        - for the insert syntax you could refer to: https://github.com/Fluidex/prover-cluster/blob/832f688759eef9b0c4454ba6e3061425eaed7a5f/migrations/20210330142700_task.sql#L36

**Comment by HAOYUatHZ** [comment]
## STEP 2

we write a L2Block every  `*test_utils::params::NTXS`, but if there's no new message coming and we wait for a too long time,

we still want to `witgen.flush_with_nop();` and write into DB.

Let's set the timeout as 2 minutes for now, but we should allow config this time parameter in the future.

So every 2 minutes, if the block is not filled (less than `*test_utils::params::NTXS`), we invoke `flush_with_nop` and generate a `L2Block`, and write it into DB.

**Comment by HAOYUatHZ** [comment]
## STEP 3

refactor the DB writing following the DBWriter style in dingir-exchange

I will explain it later

**Comment by HAOYUatHZ** [comment]
## STEP 4

refactor `replay_msgs`

for now we `self.block_sender.try_send(block)` in `replay_msgs`' `witgen`.
IMHO we could make it more readable, i.e., 
we could in fact refactor and move `block_sender` out from `witgen`,
and `try_send` directly in `replay_msgs`, after `witgen.flush_with_nop();`

**Comment by silathdiir** [comment]
I will continue working on Step 2.

**Comment by HAOYUatHZ** [comment]
> I will continue working on Step 2.

@silathdiir step2 and step4 can be combined together
